/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSiswaRouteImport } from './routes/dashboard/siswa'
import { Route as DashboardKelasRouteImport } from './routes/dashboard/kelas'
import { Route as DashboardGuruRouteImport } from './routes/dashboard/guru'
import { Route as DashboardWaliKelasIndexRouteImport } from './routes/dashboard/wali-kelas/index'
import { Route as DashboardDokumenIndexRouteImport } from './routes/dashboard/dokumen/index'
import { Route as DashboardWaliKelasCatatanRouteImport } from './routes/dashboard/wali-kelas/catatan'
import { Route as DashboardWaliKelasAbsensiRouteImport } from './routes/dashboard/wali-kelas/absensi'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSiswaRoute = DashboardSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKelasRoute = DashboardKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuruRoute = DashboardGuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWaliKelasIndexRoute = DashboardWaliKelasIndexRouteImport.update({
  id: '/wali-kelas/',
  path: '/wali-kelas/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDokumenIndexRoute = DashboardDokumenIndexRouteImport.update({
  id: '/dokumen/',
  path: '/dokumen/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWaliKelasCatatanRoute =
  DashboardWaliKelasCatatanRouteImport.update({
    id: '/wali-kelas/catatan',
    path: '/wali-kelas/catatan',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWaliKelasAbsensiRoute =
  DashboardWaliKelasAbsensiRouteImport.update({
    id: '/wali-kelas/absensi',
    path: '/wali-kelas/absensi',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/guru': typeof DashboardGuruRoute
  '/dashboard/kelas': typeof DashboardKelasRoute
  '/dashboard/siswa': typeof DashboardSiswaRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/wali-kelas/absensi': typeof DashboardWaliKelasAbsensiRoute
  '/dashboard/wali-kelas/catatan': typeof DashboardWaliKelasCatatanRoute
  '/dashboard/dokumen/': typeof DashboardDokumenIndexRoute
  '/dashboard/wali-kelas/': typeof DashboardWaliKelasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/guru': typeof DashboardGuruRoute
  '/dashboard/kelas': typeof DashboardKelasRoute
  '/dashboard/siswa': typeof DashboardSiswaRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/wali-kelas/absensi': typeof DashboardWaliKelasAbsensiRoute
  '/dashboard/wali-kelas/catatan': typeof DashboardWaliKelasCatatanRoute
  '/dashboard/dokumen': typeof DashboardDokumenIndexRoute
  '/dashboard/wali-kelas': typeof DashboardWaliKelasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/guru': typeof DashboardGuruRoute
  '/dashboard/kelas': typeof DashboardKelasRoute
  '/dashboard/siswa': typeof DashboardSiswaRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/wali-kelas/absensi': typeof DashboardWaliKelasAbsensiRoute
  '/dashboard/wali-kelas/catatan': typeof DashboardWaliKelasCatatanRoute
  '/dashboard/dokumen/': typeof DashboardDokumenIndexRoute
  '/dashboard/wali-kelas/': typeof DashboardWaliKelasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/guru'
    | '/dashboard/kelas'
    | '/dashboard/siswa'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/wali-kelas/absensi'
    | '/dashboard/wali-kelas/catatan'
    | '/dashboard/dokumen/'
    | '/dashboard/wali-kelas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/guru'
    | '/dashboard/kelas'
    | '/dashboard/siswa'
    | '/dashboard/users'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/wali-kelas/absensi'
    | '/dashboard/wali-kelas/catatan'
    | '/dashboard/dokumen'
    | '/dashboard/wali-kelas'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/guru'
    | '/dashboard/kelas'
    | '/dashboard/siswa'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/wali-kelas/absensi'
    | '/dashboard/wali-kelas/catatan'
    | '/dashboard/dokumen/'
    | '/dashboard/wali-kelas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/siswa': {
      id: '/dashboard/siswa'
      path: '/siswa'
      fullPath: '/dashboard/siswa'
      preLoaderRoute: typeof DashboardSiswaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kelas': {
      id: '/dashboard/kelas'
      path: '/kelas'
      fullPath: '/dashboard/kelas'
      preLoaderRoute: typeof DashboardKelasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guru': {
      id: '/dashboard/guru'
      path: '/guru'
      fullPath: '/dashboard/guru'
      preLoaderRoute: typeof DashboardGuruRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wali-kelas/': {
      id: '/dashboard/wali-kelas/'
      path: '/wali-kelas'
      fullPath: '/dashboard/wali-kelas/'
      preLoaderRoute: typeof DashboardWaliKelasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dokumen/': {
      id: '/dashboard/dokumen/'
      path: '/dokumen'
      fullPath: '/dashboard/dokumen/'
      preLoaderRoute: typeof DashboardDokumenIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wali-kelas/catatan': {
      id: '/dashboard/wali-kelas/catatan'
      path: '/wali-kelas/catatan'
      fullPath: '/dashboard/wali-kelas/catatan'
      preLoaderRoute: typeof DashboardWaliKelasCatatanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wali-kelas/absensi': {
      id: '/dashboard/wali-kelas/absensi'
      path: '/wali-kelas/absensi'
      fullPath: '/dashboard/wali-kelas/absensi'
      preLoaderRoute: typeof DashboardWaliKelasAbsensiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardGuruRoute: typeof DashboardGuruRoute
  DashboardKelasRoute: typeof DashboardKelasRoute
  DashboardSiswaRoute: typeof DashboardSiswaRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWaliKelasAbsensiRoute: typeof DashboardWaliKelasAbsensiRoute
  DashboardWaliKelasCatatanRoute: typeof DashboardWaliKelasCatatanRoute
  DashboardDokumenIndexRoute: typeof DashboardDokumenIndexRoute
  DashboardWaliKelasIndexRoute: typeof DashboardWaliKelasIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuruRoute: DashboardGuruRoute,
  DashboardKelasRoute: DashboardKelasRoute,
  DashboardSiswaRoute: DashboardSiswaRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWaliKelasAbsensiRoute: DashboardWaliKelasAbsensiRoute,
  DashboardWaliKelasCatatanRoute: DashboardWaliKelasCatatanRoute,
  DashboardDokumenIndexRoute: DashboardDokumenIndexRoute,
  DashboardWaliKelasIndexRoute: DashboardWaliKelasIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
